# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='end',
            field=models.DateField(default=b'', unique=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
