# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170503_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateField(unique=True),
        ),
    ]
