# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170503_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='name',
        ),
    ]
