# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_sprint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
