# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20170503_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateField(default=b'YYYY-MM-DD', unique=True),
        ),
    ]
