# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_sprint_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='descripiton',
            new_name='description',
        ),
    ]
