# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20170503_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='end',
        ),
    ]
