# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_sprint_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='end',
            field=models.DateField(default=b'', unique=True),
        ),
    ]
