# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_sprint_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateTimeField(unique=True),
        ),
    ]
