# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_pic',
            field=models.CharField(max_length=250),
        ),
    ]
