# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170808_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='detail',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
