# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170809_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
