# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_color_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=models.TextField(default='haha', max_length=250),
        ),
    ]
