# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170811_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('c_id', models.CharField(default='0', max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Color',
            new_name='Attribute',
        ),
        migrations.RenameModel(
            old_name='Size',
            new_name='Attribute_value',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='attribute_value',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='goods',
            name='a_id',
            field=models.CharField(default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='goods',
            name='a_value',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='goods',
            name='c_id',
            field=models.CharField(default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='goods',
            name='c_value',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='goods',
            name='stock',
            field=models.CharField(default='99', max_length=250),
        ),
    ]
