# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170812_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_value',
            name='a_id',
            field=models.CharField(default='0', max_length=250),
        ),
    ]
