# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_attribute_value_a_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='a_value',
            new_name='attributes',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='c_value',
            new_name='categorys',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='a_id',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='c_id',
        ),
    ]
