# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_goods_common_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('goods_pics', models.CharField(max_length=250)),
                ('categorys', models.TextField(default='null')),
                ('attributes', models.TextField(default='null')),
                ('def_goods_id', models.CharField(default='0', max_length=250)),
                ('goods_ids', models.CharField(default='0', max_length=250)),
            ],
        ),
    ]
