# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_common'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute_value',
            new_name='AttributeValue',
        ),
        migrations.RenameModel(
            old_name='Category_value',
            new_name='CategoryValue',
        ),
        migrations.AlterField(
            model_name='common',
            name='goods_pics',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
