# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20170828_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(default='null', max_length=250)),
                ('attr_comb', models.CharField(default='null', max_length=250)),
                ('price', models.CharField(default='null', max_length=250)),
                ('stock', models.CharField(default='99', max_length=250)),
                ('attr_pic', models.CharField(default='null', max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryValue',
        ),
        migrations.DeleteModel(
            name='Common',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='common_id',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_pic',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='stock',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='a_name',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='goods',
            name='describe',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='goods',
            name='pic',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='goods',
            name='attributes',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='goods',
            name='categorys',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
